steps:
  - group: ":telescope: Downstream CUDA"
    steps:
      - label: ":julia: {{matrix.repo}} (Julia 1 + CUDA GPU)"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.10"
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - ext
                - lib/LuxCore/src
                - lib/LuxCore/ext
                - lib/LuxLib/src
                - lib/LuxLib/ext
                - lib/MLDataDevices/src
                - lib/MLDataDevices/ext
                - lib/WeightInitializers/src
                - lib/WeightInitializers/ext
        command: julia --code-coverage=user --color=yes --project .buildkite/scripts/downstream.jl "{{matrix.repo}}" "CUDA"
        agents:
          queue: "juliagpu"
          cuda: "*"
        if: build.message !~ /\[skip tests\]/ && build.message !~ /\[skip downstream\]/ && build.message !~ /\[skip ci\]/ && build.pull_request.labels includes "run downstream test"
        timeout_in_minutes: 60
        matrix:
          setup:
            repo:
              - "Boltz"
              - "NeuralPDE"
              - "DeepEquilibriumNetworks"
              - "NeuralOperators"

  - group: ":telescope: Downstream AMD GPU"
    steps:
      - label: ":julia: {{matrix.repo}} (Julia 1 + AMD GPU)"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.10"
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - ext
                - lib/LuxCore/src
                - lib/LuxCore/ext
                - lib/LuxLib/src
                - lib/LuxLib/ext
                - lib/MLDataDevices/src
                - lib/MLDataDevices/ext
                - lib/WeightInitializers/src
                - lib/WeightInitializers/ext
        command: julia --code-coverage=user --color=yes --project .buildkite/scripts/downstream.jl "{{matrix.repo}}" "AMDGPU"
        agents:
          queue: "juliagpu"
          rocm: "*"
          rocmgpu: "*"
        if: build.message !~ /\[skip tests\]/ && build.message !~ /\[skip downstream\]/ && build.message !~ /\[skip ci\]/ && build.pull_request.labels includes "run downstream test"
        timeout_in_minutes: 60
        matrix:
          setup:
            repo:
              - "Boltz"
              - "NeuralOperators"

env:
  SECRET_CODECOV_TOKEN: "jQ0BMTQgyZx7QGyU0Q2Ec7qB9mtE2q/tDu0FsfxvEG7/zOAGvXkyXrzIFFOQxvDoFcP+K2+hYZKMxicYdNqzr5wcxu505aNGN2GM3wyegAr+hO6q12bCFYx6qXzU9FLCCdeqINqn9gUSSOlGtWNFrbAlrTyz/D4Yo66TqBDzvaLL63FMnhCLaXW/zJt3hNuEAJaPY2O6Ze1rX2WZ3Y+i+s3uQ8aLImtoCJhPe8CRx+OhuYiTzGhynFfGntZ0738/1RN4gNM0S/hTC4gLE7XMVBanJpGh32rFaiDwW4zAyXKBrDkL3QA3MS1RvLTJxGJ085S16hCk0C4ddAhZCvIM9Q==;U2FsdGVkX1+bXdFeKMs5G79catOCyby2n07A2fg0FjVAvrjQLZ0yfvDS4paJiFikLkodho0khz2YALKb2Y0K6w=="
